; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32

; board = esp32-wroom-da module
board = esp32doit-devkit-v1
; framework = espidf
framework = arduino
lib_deps =
    gin66/FastAccelStepper @ ^0.30.6
build_flags =
    -I include
    -D FAS_USE_RMT             ; FORCE the library to use RMT instead of MCPWM
    -D CORE_DEBUG_LEVEL=0      ; Keeps the serial buffer clean for ODrive

; [env:esp32doit-devkit-v1]
; platform = espressif32
; board = esp32doit-devkit-v1
; ; framework = espidf
; framework = arduino
; lib_deps =
;     gin66/FastAccelStepper @ ^0.30.6
; build_flags =
;     -I include
;     -D FAS_USE_RMT             ; FORCE the library to use RMT instead of MCPWM
;     -D CORE_DEBUG_LEVEL=0      ; Keeps the serial buffer clean for ODrive



